version: "3.8"
services:
  dev:
    build: .
    ports:
      - "3003:3003"
    depends_on: 
      - memcached
      - prometheus_exporter
    env_file: 
      - test.env
  
  memcached:
    image: memcached
  
  telnet:
    image: mikesplain/telnet

  prometheus_exporter:
    image: prom/memcached-exporter:v0.7.0
    ports:
      - "9150:9150"
    depends_on:
      - memcached

